### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by rodrigoprestesmachado** [orion-services/users#6]
We need to implement a mechanism to the users retrieve the password from the server

**Comment by guismoreira** [comment]
1 - do a method that generates a random hash.  

2 - when creating a user, he will have the hash attribute null by default, however, when he loses the password and asks for it, it will trigger the hash generation that will store the data generated in the attribute that was null before.  

3 - the sending of the email must contain a link concatenated with the hash, to identify exactly which user requested it.  

4 - the website with the password that the user will fill in, must contain in its javascript the address of the server method and there will be a comparison of the hash sent and the hash that is in the database.  

5 - with the change completed successfully, the hash attribute returns to null

**Comment by guismoreira** [comment]
Recover password in the app

1 - do a method that generates a random hash.

2 - when creating a user, he will have the hash attribute null by default, however, when he loses the password and asks for it, it will trigger the hash generation that will store the data generated in the attribute that was null before.
 
3 - the sending of the email must contain a short hashcode

4 - the user enters the hashcode and password, if the hash is incorrect, it will not work

5 - with the change completed successfully, the hash attribute returns to null

**Comment by rodrigoprestesmachado** [comment]
I found some issues in the users services related with the forgot password feature (service and client):

- In the create user (method create) we don’t need to return the password in the user object. 

- I think if we declare the password as "private transient String password;" will be enough to solve the question
 
- I don't know what happened but I could login in the system
 
- What is the "Auth:" in the retrieve user feature in “users” client?
 
- When we try to create a user with an e-mail the already exists in the base, the system (service and client) needs to inform the user about that, so, we need to handle both exceptions in the client and service
 
- What is the "ID" to list a user? if the send a wrong value the system (client and service) needs to inform about that
